### ISSUE TITLE
将密码存在缓存中，怎么保证安全性

### ISSUE THREAD

**Issue by zlrlyy** [xuerzong/auth-manager#6]

**Comment by xuerzong** [comment]
如果您觉得将密码存在缓存中不能保证安全性，您可以重写

- [/src/services/account.ts](https://github.com/xuerzong/auth-manager/blob/master/src/services/account.ts)
-  [/src/services/tag.ts](https://github.com/xuerzong/auth-manager/blob/master/src/services/tag.ts)

中的`get`和`set`方法，将它们指定为您想要的储存方式，例如与后端API进行交互。
